FROM node:alpine

WORKDIR '/app'

COPY package.json .

RUN npm install

COPY . .

CMD ["npm", "run", "start"]


 # Progress : 
 #1 - npm run build 
 #2 - docker build -f Dockerfile.dev .
 #3 - docker run -it -p 3000:3000 IMAGE_ID
 #4 - docker run -it -p 3000:3000 -v$(pwd):/app IMAGE_ID
 #5 - docker run -it -p 3000:3000 -v /app/node_modules -v ${PWD}:/app -e CHOKIDAR_USEPOLLING=true IMAGE_ID
 #6 - docker-compose up

 #7 - docker build -f Dockerfile.dev .  => docker run -it IMAGE_ID npm run test 
 #8 - docker exec -it ebabf868e878 npm run test           (for live testing)
 #9 - Adding a test container inside the docker-compose file 
